In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [176]:
data = pd.read_csv('Cleaned Twitter.csv')
data

Unnamed: 0                                             twitts  sentiment
0              0                                             having          0
1              1                                      sad hour away          0
2              2  skdev ah thats paranoia hate needles ve needle...          0
3              3     damn caught product searching sleep office epi          0
4              4   miss hug goat stupid photography wanted hug goat          0
...          ...                                                ...        ...
3995        3995  nickygeezy start necessary possible suddenly i...          4
3996        3996  ehhh wanna goodwill sudden urges guess heading...          4
3997        3997               accepted hospital search khaki pants          4
3998        3998       imogenheap great voice fever ray thanks link          4
3999        3999  naomichappell simple rules world better place ...          4

[4000 rows x 3 columns]

In [177]:
data.drop(columns = ['Unnamed: 0'], inplace = True)
data

twitts  sentiment
0                                                having          0
1                                         sad hour away          0
2     skdev ah thats paranoia hate needles ve needle...          0
3        damn caught product searching sleep office epi          0
4      miss hug goat stupid photography wanted hug goat          0
...                                                 ...        ...
3995  nickygeezy start necessary possible suddenly i...          4
3996  ehhh wanna goodwill sudden urges guess heading...          4
3997               accepted hospital search khaki pants          4
3998       imogenheap great voice fever ray thanks link          4
3999  naomichappell simple rules world better place ...          4

[4000 rows x 2 columns]

In [178]:
data['sentiment'].value_counts()

4    2000
0    2000
Name: sentiment, dtype: int64

In [179]:
data['twitts'].isnull().sum()

12

In [180]:
Nan_val = data['twitts'].isnull()
Nan_val

0       False
1       False
2       False
3       False
4       False
        ...  
3995    False
3996    False
3997    False
3998    False
3999    False
Name: twitts, Length: 4000, dtype: bool

In [181]:
data.drop(index = data[Nan_val].index, inplace = True)
data.reset_index(drop = True, inplace = True)  #here resetting index after dropping nan values.

In [182]:
data['sentiment'].value_counts()

4    1995
0    1993
Name: sentiment, dtype: int64

In [183]:
data['twitts'].isnull().sum()

0

In [184]:
data

twitts  sentiment
0                                                having          0
1                                         sad hour away          0
2     skdev ah thats paranoia hate needles ve needle...          0
3        damn caught product searching sleep office epi          0
4      miss hug goat stupid photography wanted hug goat          0
...                                                 ...        ...
3983  nickygeezy start necessary possible suddenly i...          4
3984  ehhh wanna goodwill sudden urges guess heading...          4
3985               accepted hospital search khaki pants          4
3986       imogenheap great voice fever ray thanks link          4
3987  naomichappell simple rules world better place ...          4

[3988 rows x 2 columns]

In [77]:
y = data['sentiment']

### Bag of Words Creation

In [78]:
cv = CountVectorizer()
text_counts = cv.fit_transform(data['twitts'])

In [79]:

text_counts.shape

(3988, 9309)

In [80]:
print(text_counts.toarray().shape)
text_counts.toarray()


(3988, 9309)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [90]:
data_bow = pd.DataFrame(text_counts.toarray(), columns = cv.get_feature_names())  # we can also remove "columns" argument..

In [91]:
data_bow

00  000  0000001  04  04071991  05  06  08  09  10  ...  zombies  zombz  \
0      0    0        0   0         0   0   0   0   0   0  ...        0      0   
1      0    0        0   0         0   0   0   0   0   0  ...        0      0   
2      0    0        0   0         0   0   0   0   0   0  ...        0      0   
3      0    0        0   0         0   0   0   0   0   0  ...        0      0   
4      0    0        0   0         0   0   0   0   0   0  ...        0      0   
...   ..  ...      ...  ..       ...  ..  ..  ..  ..  ..  ...      ...    ...   
3983   0    0        0   0         0   0   0   0   0   0  ...        0      0   
3984   0    0        0   0         0   0   0   0   0   0  ...        0      0   
3985   0    0        0   0         0   0   0   0   0   0  ...        0      0   
3986   0    0        0   0         0   0   0   0   0   0  ...        0      0   
3987   0    0        0   0         0   0   0   0   0   0  ...        0      0   

      zoo  zooloretto  zoomtext  zootopiaa  zubinsaxena  zwinky101  zynga  \
0       0           0         0          0            0          0      0   
1       0           0         0          0            0          0      0   
2       0           0         0          0            0          0      0   
3       0           0         0          0            0          0      0   
4       0           0         0          0            0          0      0   
...   ...         ...       ...        ...          ...        ...    ...   
3983    0           0         0          0            0          0      0   
3984    0           0         0          0            0          0      0   
3985    0           0         0          0            0          0      0   
3986    0           0         0          0            0          0      0   
3987    0           0         0          0            0          0      0   

      zzzzzs  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
3983       0  
3984       0  
3985       0  
3986       0  
3987       0  

[3988 rows x 9309 columns]

### ML Algorithms

In [83]:
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import MinMaxScaler

In [92]:
sgd = SGDClassifier(n_jobs= -1, random_state=42, max_iter=200) 
#n_jobs = -1 -- states that it utilises all availabel cpu's while training data...
lgr = LogisticRegression(random_state=42, max_iter=200)
lgrcv = LogisticRegressionCV(cv = 2, random_state=42, max_iter = 1000)  #it requires more iterations....cv- cross validation..
svm = LinearSVC(random_state=42, max_iter=200)
rfc = RandomForestClassifier(random_state=42, n_jobs= -1, n_estimators= 200)

In [93]:
clf = {'SGD': sgd, 'LGR':lgr, 'LGR-CV':lgrcv, 'SVM':svm, 'RFC': rfc}

In [94]:
clf.keys()

dict_keys(['SGD', 'LGR', 'LGR-CV', 'SVM', 'RFC'])

In [95]:
def classify(x,y):
    scaler = MinMaxScaler(feature_range=(0,1))
    x = scaler.fit_transform(x)
    
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42, stratify = y)
    
    for key in clf.keys():
        clf[key].fit(x_train, y_train)
        y_pred = clf[key].predict(x_test)
        ac = accuracy_score(y_test, y_pred)
        print(key, "--->", ac)

In [96]:
%%time
classify(data_bow, y)

SGD ---> 0.6604010025062657
LGR ---> 0.6791979949874687
LGR-CV ---> 0.6879699248120301
SVM ---> 0.6766917293233082
RFC ---> 0.6691729323308271
Wall time: 53.8 s


# TF-IDF

In [174]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [185]:
data.shape

(3988, 2)

In [186]:
tfidf = TfidfVectorizer()
x = tfidf.fit_transform(data['twitts'])
x.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [187]:
%%time
classify(pd.DataFrame(x.toarray()),y)

SGD ---> 0.6553884711779449
LGR ---> 0.6804511278195489
LGR-CV ---> 0.6854636591478697
SVM ---> 0.6641604010025063
RFC ---> 0.6904761904761905
Wall time: 52.7 s


# Word2Vec

In [162]:
import spacy
nlp = spacy.load('en_core_web_lg')

In [163]:
def get_vec(x):
    doc = nlp(x)
    return doc.vector.reshape(1,-1)

In [164]:
data['vec'] = data['twitts'].apply(lambda x: get_vec(x))

In [165]:
data

twitts  sentiment  \
0                                                having          0   
1                                         sad hour away          0   
2     skdev ah thats paranoia hate needles ve needle...          0   
3        damn caught product searching sleep office epi          0   
4      miss hug goat stupid photography wanted hug goat          0   
...                                                 ...        ...   
3983  nickygeezy start necessary possible suddenly i...          4   
3984  ehhh wanna goodwill sudden urges guess heading...          4   
3985               accepted hospital search khaki pants          4   
3986       imogenheap great voice fever ray thanks link          4   
3987  naomichappell simple rules world better place ...          4   

                                                    vec  
0     [[0.11235, 0.21697, -0.2109, 0.16637, 0.096581...  
1     [[0.11808103, 0.19551666, 0.169845, 0.14189333...  
2     [[-0.079496056, 0.16768679, -0.3158649, -0.064...  
3     [[-0.14417098, 0.041018147, -0.20077585, 0.007...  
4     [[-0.3998564, -0.030679878, -0.17085375, 0.012...  
...                                                 ...  
3983  [[0.009054126, 0.15927613, -0.29844663, 0.0477...  
3984  [[-0.030560374, 0.18102586, -0.13722971, 0.104...  
3985  [[0.0748146, -0.1455998, -0.122419596, 0.04719...  
3986  [[-0.19900715, 0.14350842, -0.12358614, 0.1079...  
3987  [[-0.07308651, 0.11608257, -0.11986714, -0.056...  

[3988 rows x 3 columns]

In [166]:
import numpy as np
x = np.concatenate(data['vec'].to_numpy(), axis = 0)
x


array([[ 0.11235   ,  0.21697   , -0.2109    , ..., -0.0016639 ,
        -0.017232  ,  0.03535   ],
       [ 0.11808103,  0.19551666,  0.169845  , ...,  0.16940267,
        -0.35529998,  0.12712733],
       [-0.07949606,  0.16768679, -0.3158649 , ...,  0.0217734 ,
        -0.10105007,  0.16023867],
       ...,
       [ 0.0748146 , -0.1455998 , -0.1224196 , ...,  0.0854774 ,
         0.1120398 ,  0.08975799],
       [-0.19900715,  0.14350842, -0.12358614, ..., -0.05082624,
        -0.13873042,  0.33091715],
       [-0.07308651,  0.11608257, -0.11986714, ..., -0.104865  ,
         0.20478792,  0.14561956]], dtype=float32)

In [167]:
data

twitts  sentiment  \
0                                                having          0   
1                                         sad hour away          0   
2     skdev ah thats paranoia hate needles ve needle...          0   
3        damn caught product searching sleep office epi          0   
4      miss hug goat stupid photography wanted hug goat          0   
...                                                 ...        ...   
3983  nickygeezy start necessary possible suddenly i...          4   
3984  ehhh wanna goodwill sudden urges guess heading...          4   
3985               accepted hospital search khaki pants          4   
3986       imogenheap great voice fever ray thanks link          4   
3987  naomichappell simple rules world better place ...          4   

                                                    vec  
0     [[0.11235, 0.21697, -0.2109, 0.16637, 0.096581...  
1     [[0.11808103, 0.19551666, 0.169845, 0.14189333...  
2     [[-0.079496056, 0.16768679, -0.3158649, -0.064...  
3     [[-0.14417098, 0.041018147, -0.20077585, 0.007...  
4     [[-0.3998564, -0.030679878, -0.17085375, 0.012...  
...                                                 ...  
3983  [[0.009054126, 0.15927613, -0.29844663, 0.0477...  
3984  [[-0.030560374, 0.18102586, -0.13722971, 0.104...  
3985  [[0.0748146, -0.1455998, -0.122419596, 0.04719...  
3986  [[-0.19900715, 0.14350842, -0.12358614, 0.1079...  
3987  [[-0.07308651, 0.11608257, -0.11986714, -0.056...  

[3988 rows x 3 columns]

In [168]:
x.shape

(3988, 300)

In [169]:
classify(pd.DataFrame(x), y)

SGD ---> 0.6842105263157895


c:\users\91939\desktop\python_programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:760: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LGR ---> 0.7218045112781954
LGR-CV ---> 0.7230576441102757


c:\users\91939\desktop\python_programs\python\python38\lib\site-packages\sklearn\svm\_base.py:974: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


SVM ---> 0.7055137844611529
RFC ---> 0.6879699248120301


#### Prediction using word2vec

In [172]:
def predict_w2v(x):
    for key in clf.keys():
        doc = nlp(x)
        doc =doc.vector.reshape(1,-1)
        y_pred = clf[key].predict(doc)
        print(key, "--->", y_pred)

In [173]:
predict_w2v('hi, thanks for watching this video. Please like')

SGD ---> [4]
LGR ---> [4]
LGR-CV ---> [4]
SVM ---> [4]
RFC ---> [4]


In [142]:
predict_w2v('this is worst video as i seen earlier')

SGD ---> [0]
LGR ---> [0]
LGR-CV ---> [0]
SVM ---> [0]
RFC ---> [4]
