# GloVe Vectors

Glove Vectors: https://nlp.stanford.edu/projects/glove/

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding,Activation,Dropout
from tensorflow.keras.layers import Conv1D,MaxPooling1D,GlobalMaxPooling1D
from tensorflow.keras.optimizers import Adam

import numpy as np
import pandas as pd
from numpy import array

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('spam.csv')
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will �_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [4]:
df.drop(columns = ['Unnamed: 2','Unnamed: 3','Unnamed: 4'], inplace = True)
df.columns = ['sentiment','review']
df.head()

sentiment                                             review
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df['spam'] = pd.get_dummies(df['sentiment'],drop_first=True)
df

sentiment                                             review  spam
0          ham  Go until jurong point, crazy.. Available only ...     0
1          ham                      Ok lar... Joking wif u oni...     0
2         spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3          ham  U dun say so early hor... U c already then say...     0
4          ham  Nah I don't think he goes to usf, he lives aro...     0
...        ...                                                ...   ...
5567      spam  This is the 2nd time we have tried 2 contact u...     1
5568       ham              Will �_ b going to esplanade fr home?     0
5569       ham  Pity, * was in mood for that. So...any other s...     0
5570       ham  The guy did some bitching but I acted like i'd...     0
5571       ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [6]:
df.drop(columns = ['sentiment'], inplace=True)
df

review  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568              Will �_ b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [7]:
import re
df['review'] = df['review'].apply(lambda x : re.sub(r'(http|ftp|https)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', x))
df

review  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568              Will �_ b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [8]:
df['review'] = df['review'].apply(lambda x: re.sub('�', ' ', x))

df

review  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568              Will  _ b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [9]:
from bs4 import BeautifulSoup

df['review'] = df['review'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

In [10]:
df

review  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568              Will  _ b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [11]:
df['review'].isnull().sum()

0

In [12]:
df['spam'].value_counts()

0    4825
1     747
Name: spam, dtype: int64

In [13]:
text = df['review'].tolist()
text[:3]

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
 'Ok lar... Joking wif u oni...',
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]

In [14]:
y = df['spam']

In [15]:
token = Tokenizer()
token.fit_on_texts(text)

In [16]:
vocab_size = len(token.word_index)+1
vocab_size

8821

In [17]:
token.index_word

{1: 'i',
 2: 'to',
 3: 'you',
 4: 'a',
 5: 'the',
 6: 'u',
 7: 'and',
 8: 'in',
 9: 'is',
 10: 'me',
 11: 'my',
 12: 'for',
 13: 'your',
 14: 'it',
 15: 'of',
 16: 'call',
 17: 'have',
 18: 'on',
 19: '2',
 20: 'that',
 21: 'now',
 22: 'are',
 23: 'so',
 24: 'but',
 25: 'not',
 26: 'or',
 27: 'can',
 28: 'do',
 29: 'at',
 30: "i'm",
 31: 'get',
 32: 'be',
 33: 'will',
 34: 'if',
 35: 'ur',
 36: 'with',
 37: 'just',
 38: 'no',
 39: 'we',
 40: 'this',
 41: '4',
 42: 'up',
 43: 'when',
 44: 'ok',
 45: 'free',
 46: 'how',
 47: 'go',
 48: 'from',
 49: 'all',
 50: 'out',
 51: 'what',
 52: 'know',
 53: 'like',
 54: 'good',
 55: 'then',
 56: 'got',
 57: 'was',
 58: 'come',
 59: 'its',
 60: 'am',
 61: 'day',
 62: 'time',
 63: 'only',
 64: 'love',
 65: 'there',
 66: 'send',
 67: 'he',
 68: 'want',
 69: 'text',
 70: 'as',
 71: 'txt',
 72: 'one',
 73: 'going',
 74: 'by',
 75: '1',
 76: 'home',
 77: "i'll",
 78: 'need',
 79: 'about',
 80: 'r',
 81: 'lor',
 82: 'sorry',
 83: 'stop',
 84: 'still',
 8

In [18]:
encoded_text = token.texts_to_sequences(text)
encoded_text[:3]

[[47,
  469,
  4368,
  832,
  745,
  653,
  63,
  8,
  1310,
  86,
  118,
  350,
  1311,
  147,
  2959,
  1312,
  65,
  56,
  4369,
  142],
 [44, 336, 1481, 470, 6, 1909],
 [45,
  484,
  8,
  19,
  4,
  788,
  890,
  2,
  176,
  1910,
  1184,
  654,
  1911,
  2298,
  261,
  2299,
  69,
  1910,
  2,
  1912,
  2,
  337,
  484,
  551,
  948,
  71,
  387,
  136,
  655,
  388,
  2960]]

In [19]:
#getting maximum length of array indexes of encoded_text

max_ = []
def get_max_len(x):
    for i in x[:]:
        max_.append(len(i))
    
    length = np.max(max_)
    return length

max_length = get_max_len(encoded_text)
max_length

189

In [20]:
#knowing maximum index of encoded_text having maximum length of array

max_ = []
def get_max_ind(x):
    for i in x[:]:
        max_.append(len(i))
    k=0   
    for j in max_:
        if j == max_length:
            index = k
        k+=1 
    return index
max_index =get_max_ind(encoded_text)
print(max_index)

1084


In [21]:
encoded_text[max_index]

[12,
 10,
 5,
 64,
 146,
 360,
 36,
 5230,
 1,
 146,
 208,
 20,
 1,
 78,
 102,
 183,
 62,
 214,
 10,
 94,
 146,
 32,
 5,
 203,
 213,
 218,
 583,
 8,
 11,
 3462,
 1,
 174,
 360,
 5,
 61,
 7,
 319,
 14,
 36,
 102,
 94,
 146,
 32,
 65,
 183,
 62,
 1,
 968,
 64,
 33,
 32,
 55,
 43,
 11,
 183,
 3463,
 116,
 102,
 263,
 11,
 166,
 146,
 614,
 214,
 102,
 11,
 166,
 33,
 32,
 3352,
 2,
 102,
 1,
 174,
 1714,
 12,
 102,
 33,
 141,
 49,
 11,
 877,
 7,
 96,
 49,
 102,
 5231,
 1,
 33,
 32,
 311,
 2,
 2140,
 36,
 710,
 12,
 102,
 1,
 33,
 32,
 8,
 64,
 43,
 1,
 33,
 32,
 157,
 5,
 3464,
 249,
 12,
 102,
 64,
 33,
 32,
 43,
 1,
 97,
 17,
 2,
 5232,
 710,
 20,
 11,
 364,
 9,
 5,
 452,
 596,
 1555,
 18,
 5,
 796,
 3465,
 1,
 33,
 236,
 32,
 3466,
 5233,
 12,
 102,
 64,
 33,
 32,
 43,
 1,
 360,
 42,
 537,
 2605,
 3467,
 7,
 319,
 42,
 5234,
 5235,
 166,
 33,
 32,
 5,
 452,
 596,
 55,
 33,
 31,
 183,
 169,
 7,
 440,
 335,
 12,
 5,
 61,
 331,
 94,
 9,
 36,
 10,
 1,
 174,
 53,
 2,
 150,
 4,
 346,
 33,
 9

In [22]:
max_len = max_length + 11
max_len

200

In [23]:
max_len = max_len
X = pad_sequences(encoded_text, maxlen = max_len, padding = 'post')
X.shape

(5572, 200)

In [24]:
X

array([[  47,  469, 4368, ...,    0,    0,    0],
       [  44,  336, 1481, ...,    0,    0,    0],
       [  45,  484,    8, ...,    0,    0,    0],
       ...,
       [8818,   57,    8, ...,    0,    0,    0],
       [   5,  530,  113, ...,    0,    0,    0],
       [2652,   59,  462, ...,    0,    0,    0]])

# GloVe Vectors

In [25]:
glove_vectors = dict()

Now we have to make a dictionary as `{'words' : vectors of each word}` from `GloVe models/glove.6B.200d.txt` file (200d - 200dimensional)

In [26]:
file = open('GloVe models/glove.6B.200d.txt', encoding = 'utf-8')

for line in file:
    values = line.split()
    word = values[0]
    vectors = np.asarray(values[1:])
    glove_vectors[word] = vectors
file.close()

In [27]:
keys = glove_vectors.keys()
list(keys)[:15]

['the',
 ',',
 '.',
 'of',
 'to',
 'and',
 'in',
 'a',
 '"',
 "'s",
 'for',
 '-',
 'that',
 'on',
 'is']

In [28]:
len(glove_vectors.keys())

400000

In [29]:
glove_vectors.get('you').shape

(200,)

In [30]:
a =glove_vectors.get('asciii')
print(a)

None


## matching and making a vector of words present in glove_vectors

In [31]:
word_vector_matrix = np.zeros((vocab_size, max_len))
word_vector_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
for word, index in token.word_index.items():
    vector = glove_vectors.get(word)
    
    if vector is not None:
        word_vector_matrix[index] = vector
    else:
        print(word)

i'm
i'll
don't
it's
150p
i've
can't
that's
you're
didn't
150ppm
aight
thanx
he's
how's
there's
we're
won't
haven't
what's
8007
we'll
chikku
86688
c's
she's
12hrs
msgs
knw
pobox
08000930705
frnd
boytoy
mobileupd8
doesn't
you've
oredi
suite342
2lands
08000839402
wkly
freemsg
frnds
you'll
ni8
savamob
mrng
87066
bslvyl
txts
mayb
i'd
askd
call2optout
wasn't
rply
isn't
txting
bcoz
w1j6hl
callertune
custcare
rakhesh
getzed
ldew
11mths
urself
age16
comuk
87077
you'd
ip4
5we
where's
rcvd
fullonsms
t's
polys
08712460324
frens
joy's
bx420
82277
uk's
yijue
08718720201
some1
today's
85023
unsub
omw
izzit
shuhui
yest
they're
36504
sk38xh
u'll
alrite
cr9
5wb
lmao
thnk
who's
wat's
vikky
god's
150pm
08712300220
62468
u've
aathi
vry
ttyl
40gb
l8r
aiyo
evng
u're
aftr
txtauction
pobox84
w45wq
norm150p
sipix
aiyah
howz
let's
thts
08707509020
86021
09050090044
toclaim
pobox334
max10mins
nimya
urgnt
shouldn't
ec2a
2optout
themob
aren't
he'll
sonyericsson
geeee
did't
pobox36504w45wq
she'll
83355
2mrw
yogasana

bold2
09094100151
gbp5
box61
thkin
resubbing
09066362220
yelow
drugdealer
23f
23g
wondarfull
web2mobile
txt250
box139
la32wu
txtx
onbus
donyt
latelyxxx
85233
tming
08700469649
box420
howda
samachara
audrie
087123002209am
washob
nobbing
intha
ponnungale
ipaditan
needa
marsms
b4utele
08717168528
2getha
qlynnbv
help08700621170150p
waaaat
lololo
table's
stapati
shakara
crickiting
dontmatter
urgoin
outl8r
yavnt
ibuprofens
claypot
fishhead
beehoon
jaklin
avble
4got
aluable
ffectionate
oveable
ternal
oble
ruthful
ntimate
atural
namous
textin'
weren't
waliking
08714712379
k718
09065069120
smidgin
accordin
no's
listened2the
air1
braindance
ofstuff
bb's
unmits
yummmm
puzzeles
4goten
09099726481
r836
09065069154
shifad
'doctors'
splashmobile
subscrition
88877
3pound
all's
brdget
inever
velly
2stoptx
08718738034
08718726971
tddnewsletter
emc1
thedailydraw
prizeswith
zyada
milta
sochte
jeetey
varaya
elaya
09066368753
97n7qp
workand
whilltake
zogtorius
or2optout
hv9d
frwd
buddys
08712402902
monoc
po

09064017295
ofcourse
08448350055
planettalkinstant
83338
07808247860
08719899229
40411
referin
mei's
colany
49557
tantrum's
gsex
2667
wc1n
3mobile
chatlines
inclu
servs
l8er
childporn
pshew
4years
nmde
087187272008
now1


word_vector_matrix -- contains the weights from glove vectors for each matched word in X and remaining unmatched words make into zeroes...


In [33]:

word_vector_matrix

array([[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [ 0.26805 ,  0.36032 , -0.332   , ...,  0.17769 ,  0.22362 ,
         0.014241],
       [ 0.57346 ,  0.5417  , -0.23477 , ...,  0.54418 , -0.23069 ,
         0.34947 ],
       ...,
       [ 0.10072 ,  0.63531 ,  0.12209 , ...,  0.58416 , -0.3626  ,
        -0.12722 ],
       [ 0.49325 ,  0.19096 ,  0.5253  , ..., -0.4833  , -0.11912 ,
         0.44662 ],
       [-0.026745,  0.21534 , -0.11869 , ..., -0.41846 , -0.13528 ,
         0.19105 ]])

In [34]:
word_vector_matrix.shape

(8821, 200)

word_vector_matrix --- It has the weights for corresponding numbers in X

## Model Building with Keras

In [35]:
X

array([[  47,  469, 4368, ...,    0,    0,    0],
       [  44,  336, 1481, ...,    0,    0,    0],
       [  45,  484,    8, ...,    0,    0,    0],
       ...,
       [8818,   57,    8, ...,    0,    0,    0],
       [   5,  530,  113, ...,    0,    0,    0],
       [2652,   59,  462, ...,    0,    0,    0]])

In [36]:
X_train ,X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size = 0.2, stratify = y)

In [37]:
vec_size=200 
#changing each word in an index into a vector of size 200

In [38]:
model = Sequential()
model.add(Embedding(vocab_size, vec_size, input_length = max_len, weights = [word_vector_matrix], trainable = False))

model.add(Conv1D(64, 8, activation = 'relu'))
model.add(Conv1D(64, 8, activation = 'relu'))
model.add(MaxPooling1D(2))

model.add(Flatten())
model.add(Dense(32, kernel_initializer = 'he_normal',activation = 'relu'))
model.add(Dropout(0.25))

model.add(Dense(16, kernel_initializer = 'he_normal', activation='relu'))
#model.add(GlobalMaxPooling1D())

model.add(Dense(1, activation='sigmoid'))



In [39]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 200, 200)          1764200   
_________________________________________________________________
conv1d (Conv1D)              (None, 193, 64)           102464    
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 186, 64)           32832     
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 93, 64)            0         
_________________________________________________________________
flatten (Flatten)            (None, 5952)              0         
_________________________________________________________________
dense (Dense)                (None, 32)                190496    
_________________________________________________________________
dropout (Dropout)            (None, 32)                0

In [40]:
model.compile(optimizer=Adam(learning_rate=0.001), loss = 'binary_crossentropy',metrics = ['accuracy'])

In [41]:
model.fit(X_train, y_train, epochs = 12, validation_data = (X_test,y_test))

Epoch 1/12
140/140 [==============================] - 6s 46ms/step - loss: 0.1944 - accuracy: 0.9293 - val_loss: 0.0851 - val_accuracy: 0.9758
Epoch 2/12
140/140 [==============================] - 6s 45ms/step - loss: 0.0808 - accuracy: 0.9785 - val_loss: 0.0591 - val_accuracy: 0.9848
Epoch 3/12
140/140 [==============================] - 7s 52ms/step - loss: 0.0583 - accuracy: 0.9814 - val_loss: 0.0571 - val_accuracy: 0.9883
Epoch 4/12
140/140 [==============================] - 8s 55ms/step - loss: 0.0319 - accuracy: 0.9906 - val_loss: 0.0743 - val_accuracy: 0.9803
Epoch 5/12
140/140 [==============================] - 8s 55ms/step - loss: 0.0240 - accuracy: 0.9921 - val_loss: 0.0604 - val_accuracy: 0.9874
Epoch 6/12
140/140 [==============================] - 8s 55ms/step - loss: 0.0087 - accuracy: 0.9978 - val_loss: 0.1259 - val_accuracy: 0.9614
Epoch 7/12
140/140 [==============================] - 8s 55ms/step - loss: 0.0064 - accuracy: 0.9982 - val_loss: 0.0970 - val_accuracy: 0.9865

# saving our model

In [43]:
model.save('saved models/Glove Vectors spam detection.h5')

# load saved model and predict  new data

In [44]:
from tensorflow.keras.models import load_model

In [45]:
Model = load_model('saved models/Glove Vectors spam detection.h5')

In [46]:
def get_encode(x):
    x = token.texts_to_sequences(x)
    x = pad_sequences(x, maxlen = max_len, padding = 'post')
    return x

In [93]:
result = get_encode(['you won a free ticket to singapore for a tour'])

In [94]:
(model.predict(result) > 0.5).astype('int32')   #1 basically represents spam here..

array([[1]])

## predicting validation set

In [71]:
y_test[5]

1

In [87]:
result1 = X_test[5].reshape(1,-1)

In [88]:
(model.predict(result1) > 0.5).astype('int32')

array([[0]])